spring:
  datasource:
    url: jdbc:postgresql://postgresql.c7ki0kwsskvn.eu-west-1.rds.amazonaws.com:5432/housing
    username: postgres
    password: xebpe1-Paqhoj-jovpir
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
